/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehiclereservationsytem;

/**
 *
 * @author yousifabulnaga
 */
public class admingui extends javax.swing.JFrame {


    public admingui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageVehicle = new javax.swing.JRadioButton();
        viewAnalytic = new javax.swing.JRadioButton();
        respondToComplaint = new javax.swing.JRadioButton();
        addMechanic = new javax.swing.JRadioButton();
        deleteMechanic = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        viewSupplies = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Admin");

        manageVehicle.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(manageVehicle);
        manageVehicle.setForeground(new java.awt.Color(242, 242, 242));
        manageVehicle.setText("manage vehicles");
        manageVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVehicleActionPerformed(evt);
            }
        });

        viewAnalytic.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(viewAnalytic);
        viewAnalytic.setForeground(new java.awt.Color(242, 242, 242));
        viewAnalytic.setText("view analytic");
        viewAnalytic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnalyticActionPerformed(evt);
            }
        });

        respondToComplaint.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(respondToComplaint);
        respondToComplaint.setForeground(new java.awt.Color(242, 242, 242));
        respondToComplaint.setText("respond to complaint");
        respondToComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondToComplaintActionPerformed(evt);
            }
        });

        addMechanic.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(addMechanic);
        addMechanic.setForeground(new java.awt.Color(242, 242, 242));
        addMechanic.setText("add mechanic");
        addMechanic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMechanicActionPerformed(evt);
            }
        });

        deleteMechanic.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(deleteMechanic);
        deleteMechanic.setForeground(new java.awt.Color(242, 242, 242));
        deleteMechanic.setText("delete mechanic");
        deleteMechanic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMechanicActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 102, 204));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 102, 204));
        saveButton.setForeground(new java.awt.Color(242, 242, 242));
        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        viewSupplies.setBackground(new java.awt.Color(51, 52, 54));
        buttonGroup1.add(viewSupplies);
        viewSupplies.setForeground(new java.awt.Color(242, 242, 242));
        viewSupplies.setText("view supplies");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manageVehicle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(respondToComplaint))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewAnalytic))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addMechanic))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteMechanic))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewSupplies)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAnalytic)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respondToComplaint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMechanic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteMechanic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewSupplies)
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(saveButton))
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void respondToComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondToComplaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respondToComplaintActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
       if(manageVehicle.isSelected()){
        VehicleHOME v = new VehicleHOME();
        v.setVisible(true);
        this.dispose();
        } 
     
       if(respondToComplaint.isSelected()){
        respondToComplainJframe j = new respondToComplainJframe();
        j.setVisible(true);
        this.dispose();
        } 
        if( viewSupplies.isSelected()){
        viewSuppliesForm supp = new viewSuppliesForm();
        supp.setVisible(true);
        this.dispose();
        } 
        if(viewAnalytic.isSelected()){
            viewAnalytic v = new viewAnalytic();
            this.dispose();
            v.setVisible(true);
        
        }
                if(addMechanic.isSelected()){
            addMechanic v = new addMechanic();
            this.dispose();
            v.setVisible(true);
        
        }
                                if(deleteMechanic.isSelected()){
            deleteMechanic v = new deleteMechanic();
            this.dispose();
            v.setVisible(true);
        
        }
    }//GEN-LAST:event_saveButtonActionPerformed
   
    private void viewAnalyticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnalyticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAnalyticActionPerformed

    private void manageVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageVehicleActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        home m = new home();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addMechanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMechanicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMechanicActionPerformed

    private void deleteMechanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMechanicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMechanicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admingui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admingui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addMechanic;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton deleteMechanic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton manageVehicle;
    private javax.swing.JRadioButton respondToComplaint;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton viewAnalytic;
    private javax.swing.JRadioButton viewSupplies;
    // End of variables declaration//GEN-END:variables
}
