package vehiclereservationsytem;

import java.util.Date;
import vehiclereservationsytem.Appointment;
import vehiclereservationsytem.Customer;
import vehiclereservationsytem.appointmentForm;
import vehiclereservationsytem.service;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yousifabulnaga
 */
public class chooseServiceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form chooseServiceJFrame
     */
Customer c ;
    public chooseServiceJFrame() {
        initComponents();
    }
 public chooseServiceJFrame(Customer c ) {
        initComponents();
        this.c=c;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        vehiclehome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullServiceButton = new javax.swing.JRadioButton();
        maintenanceButton = new javax.swing.JRadioButton();
        RentButton = new javax.swing.JRadioButton();
        washButton = new javax.swing.JRadioButton();
        checkupButton = new javax.swing.JRadioButton();
        ChooseServiceBackButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));

        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton1.setText("Display Vehicle");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton2.setText("Delete Vehicle");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton3.setText("Display Rented Vehicle");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 102, 204));
        jRadioButton5.setText("Add Vehicle");

        vehiclehome.setBackground(new java.awt.Color(0, 102, 204));
        vehiclehome.setForeground(new java.awt.Color(255, 255, 255));
        vehiclehome.setText("Select");
        vehiclehome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclehomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("VEHICLE HOMEPAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehiclehome)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(vehiclehome)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 52, 54));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Choose Service");

        FullServiceButton.setBackground(new java.awt.Color(51, 52, 54));
        chooseBtnGroup.add(FullServiceButton);
        FullServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        FullServiceButton.setText("Full Vehicle Service");
        FullServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullServiceButtonActionPerformed(evt);
            }
        });

        maintenanceButton.setBackground(new java.awt.Color(51, 52, 54));
        chooseBtnGroup.add(maintenanceButton);
        maintenanceButton.setForeground(new java.awt.Color(255, 255, 255));
        maintenanceButton.setText("Vehicle Maintenance");
        maintenanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceButtonActionPerformed(evt);
            }
        });

        RentButton.setBackground(new java.awt.Color(51, 52, 54));
        chooseBtnGroup.add(RentButton);
        RentButton.setForeground(new java.awt.Color(255, 255, 255));
        RentButton.setText("Rent Vehicle");
        RentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentButtonActionPerformed(evt);
            }
        });

        washButton.setBackground(new java.awt.Color(51, 52, 54));
        chooseBtnGroup.add(washButton);
        washButton.setForeground(new java.awt.Color(255, 255, 255));
        washButton.setText("Vehicle Wash");
        washButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washButtonActionPerformed(evt);
            }
        });

        checkupButton.setBackground(new java.awt.Color(51, 52, 54));
        chooseBtnGroup.add(checkupButton);
        checkupButton.setForeground(new java.awt.Color(255, 255, 255));
        checkupButton.setText("Vehicle Checkup");

        ChooseServiceBackButton.setBackground(new java.awt.Color(0, 102, 204));
        ChooseServiceBackButton.setForeground(new java.awt.Color(255, 255, 255));
        ChooseServiceBackButton.setText("Back");
        ChooseServiceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseServiceBackButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 102, 204));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehiclereservationsytem/tinyW.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FullServiceButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RentButton)
                                    .addComponent(washButton)
                                    .addComponent(checkupButton)
                                    .addComponent(maintenanceButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(261, 261, 261))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseServiceBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(FullServiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maintenanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(washButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkupButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChooseServiceBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FullServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullServiceButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FullServiceButtonActionPerformed

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    private void washButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washButtonActionPerformed

    private void ChooseServiceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseServiceBackButtonActionPerformed
        // TODO add your handling code here:
        myaccount m = new myaccount(c);
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_ChooseServiceBackButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(FullServiceButton.isSelected()){
            service s = new service (1);
            //FullVehicleJFrame j = new FullVehicleJFrame();
            
            vehicleData vDate = new vehicleData(s,c);
            this.dispose();
            vDate.setVisible(true);
     
        this.dispose();
        }
       if(maintenanceButton.isSelected()){
        service s = new service (2);
            
            vehicleData vDate = new vehicleData(s,c);
            this.dispose();
            vDate.setVisible(true);
     
        this.dispose();
        }
       if(RentButton.isSelected()){
        service s = new service (3);
            
            rentForm rentForm = new rentForm(c,s);
            this.dispose();
            rentForm.setVisible(true);
            
       }
       
       if(washButton.isSelected()){
        service s = new service (4);
            vehicleData vDate = new vehicleData(s,c);
            this.dispose();
            vDate.setVisible(true);
        } 
       if(checkupButton.isSelected()){
       service s = new service (5);
            
            vehicleData vDate = new vehicleData(s,c);
            this.dispose();
            vDate.setVisible(true);
        } 
       
    
        
        
        
        
        
        
        
        
//        String selectedOption = this.chooseBtnGroup.getSelection().getActionCommand();
//                if (FullServiceButton.isSelected()) {
//                    selectedOption = "Full Vehicle Service ";
//                } else if (radio2.isSelected()) {
//                    selectedOption = "Option 2";
//                } else if (radio3.isSelected()) {
//                    selectedOption = "Option 3";
//                }
//String selection = this.chooseBtnGroup.getSelection().getActionCommand();
//        FullVehicleJFrame fv= new FullVehicleJFrame();
//        fv.setVisible(true);
//        dispose();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void RentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void vehiclehomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclehomeActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){
            DeleteVehicle j = new DeleteVehicle();
            j.setVisible(true);
            this.dispose();
        }
        if(jRadioButton3.isSelected()){
            DisplayRent j = new DisplayRent();
            j.setVisible(true);
            this.dispose();
        }
        if(jRadioButton1.isSelected()){
            DisplayVehicle j = new DisplayVehicle();
            j.setVisible(true);
            this.dispose();
        }
        if(jRadioButton5.isSelected()){
            AddVehicle j = new AddVehicle();
            j.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_vehiclehomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseServiceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseServiceJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseServiceBackButton;
    private javax.swing.JRadioButton FullServiceButton;
    private javax.swing.JRadioButton RentButton;
    private javax.swing.JRadioButton checkupButton;
    private javax.swing.ButtonGroup chooseBtnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton maintenanceButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton vehiclehome;
    private javax.swing.JRadioButton washButton;
    // End of variables declaration//GEN-END:variables
}
