/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclereservationsytem;

import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatem
 */


public class paymentForm extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
   
     ArrayList<Double> suppPrice= new ArrayList<>();
     ArrayList<String> suppName= new ArrayList<>();
     int random;
      ArrayList<Integer> randomCheckList= new ArrayList<>();
     
     database db ;  
      payment p;
      Customer c ; 
      vehicle v ;
      int serviceID;
      
      
      Boolean isMechanic=false;
      ArrayList <supply> suppList;
      Mechanic m ;
      report r = new report ();
      double billForMechanic;
      DefaultTableModel model;
      double servicePrice;
      
       public paymentForm() {
           initComponents();
       }

              public paymentForm(Mechanic m,ArrayList<supply> suppList) {
               initComponents();
               
               isMechanic=true;
                db= new database();
               this.suppList=suppList;
               this.m=m;
                  model = new DefaultTableModel();
 model = (DefaultTableModel)jTable1.getModel();
                  System.out.println("mechanic id : "+m.getId());
               for(int i =0 ;i<suppList.size();i++){
                  model.addRow(new Object []{suppList.get(i).getSupplyname(),suppList.get(i).getSupplyPrice()});
              
               }
               m.makePayment();
                m.getP().getR().calculateTotalBill(suppList);
                 
              billForMechanic=  m.getP().getR().getTotalBill();
               totalBill.setText(billForMechanic+"");
           
           
       }
       
       double totalPrice=0;
    public paymentForm(Customer c) {
           initComponents();
           db= new database ();
           p=new payment();
           
           p.setR(r);
           this.c=c;
        suppPrice= p.r.getsupplyPrice();
      suppName=p.r.getsupplyName();
     
         serviceID=db.getSeviceIdByCustID(c);
         p.r.calculateTotalBill(serviceID);
        servicePrice =p.r.getTotalBill();
        
         
   DefaultTableModel model = new DefaultTableModel();
 model = (DefaultTableModel)jTable1.getModel();

   totalBill.setText(servicePrice+"");
      
        if(serviceID==1){
        
for(int i =0 ;i<2;i++){
       random =p.r.randomSupplyConsumed();
       if(randomCheckList.contains(random))
            random++;
    totalPrice+=suppPrice.get(random);
model.addRow(new Object []{suppName.get(random),suppPrice.get(random)});
          randomCheckList.add(random);     
}


        }
        
        
        
        else if (serviceID==2){
            
model.addRow(new Object []{"vehicle Maintenance",servicePrice});
totalBill.setText(servicePrice+"");
       
        }
        
        
//heya el waheeda ely hatefta7 haga tanya 3ashan a5tar el vehicles w kol wahda 3ala hasab se3raha 
        
          else if (serviceID==3){
             // payment paymentForRent()
            
model.addRow(new Object []{"rent vehicle",servicePrice});
            System.out.println(servicePrice);
        totalBill.setText(servicePrice+"");

        }
        
             else if (serviceID==4){
            
model.addRow(new Object []{"vehicle wash",servicePrice});
totalBill.setText(servicePrice+"");
         
        }
                  else if (serviceID==5){
            
model.addRow(new Object []{"vehicle checkup",servicePrice});
totalBill.setText(servicePrice+"");
         
        }
      
        
      
    
    }
        public paymentForm(Customer c,payment p ) {
           initComponents();
            db=new database();
           this.c=c;
           this.p=p;
               model = new DefaultTableModel();
               model = (DefaultTableModel)jTable1.getModel();
              
     model.addRow(new Object []{"rent vehicle",p.getR().getTotalBill()});

               totalPrice= Double.parseDouble(jTable1.getValueAt(0, 1).toString());
                 totalBill.setText(totalPrice+"");

        }
    
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        nameEntry = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cardNumEntry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        expiryDateEntry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cvvEntry = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        totalBill = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 52, 54));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        label1.setForeground(new java.awt.Color(0, 102, 204));
        label1.setText("report");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("total Bill");

        label2.setForeground(new java.awt.Color(0, 102, 204));
        label2.setText("payment");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("card holder name ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("card number ");

        cardNumEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumEntryActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("expiry date");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("cvv");

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        totalBill.setForeground(new java.awt.Color(255, 255, 255));
        totalBill.setText("vscd");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehiclereservationsytem/tinyW.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButton2)
                                    .addGap(32, 32, 32))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(412, 412, 412))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(expiryDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(165, 165, 165)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cvvEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(150, 150, 150)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cardNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(expiryDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cvvEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       Date transactionDate= new Date();
        String cardHolderName= nameEntry.getText();
        String cardNumber = cardNumEntry.getText();
        String cvv=cvvEntry.getText();
        String expiryDate= expiryDateEntry.getText();
     String month="";
       String year="";
        if(cardHolderName.compareTo("")==0||cardNumber.compareTo("")==0 || cvv.compareTo("")==0||expiryDate.compareTo("")==0 ){

            JOptionPane.showMessageDialog(null, "please enter you payment details ","Error !", JOptionPane.ERROR_MESSAGE);
          

        }
        else{
           month=expiryDate.substring(0, 2);
          year = expiryDate.substring(3);
        

         if (cvv.length()!=3 && cvv.length()!=0){
            JOptionPane.showMessageDialog(null, "wrong in cvv","error!", JOptionPane.ERROR_MESSAGE);
        }
        else if (cardNumber.length()<16 && cardNumber.length()!=0){
            JOptionPane.showMessageDialog(null, "Enter a valid card number !","error!", JOptionPane.ERROR_MESSAGE);
            
        }
         
          else if (Integer.parseInt(year)<2023){
                JOptionPane.showMessageDialog(null, "Enter a valid expiry date !","error", JOptionPane.ERROR_MESSAGE);
              
          }
          else {
          if(isMechanic==true){
          m.getP().setCardHolderNum(cardNumber);
          m.getP().setCardholderName(cardHolderName);
          m.getP().setPaymentDate(transactionDate.toString());
          m.getP().getR().calculateBillForMechanic();
             db.savepayment(m.getP().getPaymentID(),m.getP().getCardHolderNum(),m.getP().getCardholderName(),m.getId());
             db.saveReport(m.getP().getR().getTotalBill(), m.getP().getPaymentID());
             db.addRevenueToDb(m.getP().getR().getTotalBill());
             JOptionPane.showMessageDialog(null, "Purchase successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

          }
         
          else {
         p.setC(c);
         p.setCardHolderNum(cardNumber);
         p.setCardholderName(cardHolderName);
         p.setPaymentDate(transactionDate.toString());
        db.savepayment(p);
        db.saveReport(totalPrice, p.getPaymentID());
              System.out.println("total price : "+totalPrice);
        db.addRevenueToDb(totalPrice);
  JOptionPane.showMessageDialog(null, "Purchase successful!", "Success", JOptionPane.INFORMATION_MESSAGE);


         
         
          }
           
       
          }
        }
       
          
         
          
          
      
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cardNumEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumEntryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(isMechanic){
        mechanicJframe acc= new mechanicJframe(m);
        this.dispose();
        acc.setVisible(true);
        }
        else{
            myaccount m = new myaccount (c);
            this.dispose();
            m.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardNumEntry;
    private javax.swing.JTextField cvvEntry;
    private javax.swing.JTextField expiryDateEntry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField nameEntry;
    private javax.swing.JLabel totalBill;
    // End of variables declaration//GEN-END:variables
}
